# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/OrganisationServiceDB
spring.datasource.username=postgres
spring.datasource.password=madhav99

spring.datasource.driver-class-name=org.postgresql.Driver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarthak.hti@gmail.com
spring.mail.password=fshz kbii fnep gfgg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.reset-password.expiry-minutes=15
app.reset-password.base-url=http://localhost:9329

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

crypto.secret-key=1234567890123456
# ===============================
# SWAGGER
# ===============================

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# ===============================
# SERVER
# ===============================

server.port=9329